const {
  NODE_ENV = 'dev',
  PORT = 8002,
  TRELLO_API_KEY,
  TRELLO_API_TOKEN,
  TRELLO_TECHNICAL_ISSUE_LIST_ID,
  TRELLO_SUPPORT_TICKET_LIST_ID,
  REACT_APP_GOOGLE_ANALYTICS_ID,
  RECAPTCHA_SECRET_KEY,
  FOODFEED_EMAIL_ADDRESS,
  FOODFEED_SUPPORT_EMAIL,
  REACT_APP_GAUTH_CLIENTID,
  GAUTH_CLIENT_SECRET,
  FOODFEED_GMAIL_REFRESH_TOKEN,
  DATABASE_URL
} = process.env;

const IS_PRODUCTION = NODE_ENV === 'production';

const envs = [
  NODE_ENV,
  PORT,
  IS_PRODUCTION,
  TRELLO_API_KEY,
  TRELLO_API_TOKEN,
  TRELLO_TECHNICAL_ISSUE_LIST_ID,
  TRELLO_SUPPORT_TICKET_LIST_ID,
  REACT_APP_GOOGLE_ANALYTICS_ID,
  RECAPTCHA_SECRET_KEY,
  FOODFEED_EMAIL_ADDRESS,
  FOODFEED_SUPPORT_EMAIL,
  REACT_APP_GAUTH_CLIENTID,
  GAUTH_CLIENT_SECRET,
  FOODFEED_GMAIL_REFRESH_TOKEN,
  DATABASE_URL
];

if (!envs.every((env) => env !== undefined)) {
  throw new Error('Some environment variables are undefined');
}

export {
  NODE_ENV,
  PORT,
  IS_PRODUCTION,
  TRELLO_API_KEY,
  TRELLO_API_TOKEN,
  TRELLO_TECHNICAL_ISSUE_LIST_ID,
  TRELLO_SUPPORT_TICKET_LIST_ID,
  REACT_APP_GOOGLE_ANALYTICS_ID,
  RECAPTCHA_SECRET_KEY,
  FOODFEED_EMAIL_ADDRESS,
  FOODFEED_SUPPORT_EMAIL,
  REACT_APP_GAUTH_CLIENTID,
  GAUTH_CLIENT_SECRET,
  FOODFEED_GMAIL_REFRESH_TOKEN,
  DATABASE_URL
};
