/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v0.1.43), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

import type {
  //@ts-ignore
  JSONValue,
  //@ts-ignore
  JSONArray,
  DateString,
  SQLFragment,
  //@ts-ignore
  SQL,
  GenericSQLExpression,
  ColumnNames,
  ColumnValues,
  ParentColumn,
  DefaultType
} from './src/core';

/* === schema: public === */

/* --- enums --- */

export type call_rating_enum = 'bad' | 'good';
export namespace every {
  export type call_rating_enum = ['bad', 'good'];
}
export type users_devices_platform_enum = 'android' | 'ios';
export namespace every {
  export type users_devices_platform_enum = ['android', 'ios'];
}
export type users_gender_enum = 'F' | 'M' | 'O' | 'U';
export namespace every {
  export type users_gender_enum = ['F', 'M', 'O', 'U'];
}
export type users_posts_media_types_enum = 'image' | 'video';
export namespace every {
  export type users_posts_media_types_enum = ['image', 'video'];
}
export type users_reported_types_enum = 'call' | 'post' | 'stream';
export namespace every {
  export type users_reported_types_enum = ['call', 'post', 'stream'];
}
export type users_stream_reactions_enum = 'downvote' | 'upvote';
export namespace every {
  export type users_stream_reactions_enum = ['downvote', 'upvote'];
}

/* --- tables --- */

export namespace faqs {
  export type Table = 'faqs';
  export interface Selectable {
    id: string;
    question: string;
    answer: string;
    createdAt: Date;
    updatedAt: Date;
  }
  export interface Insertable {
    id?: string | DefaultType | SQLFragment;
    question: string | SQLFragment;
    answer: string | SQLFragment;
    createdAt?: Date | DateString | DefaultType | SQLFragment;
    updatedAt?: Date | DateString | DefaultType | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> {}
  export type Whereable = {
    [K in keyof Insertable]?: Exclude<
      Insertable[K] | ParentColumn,
      null | DefaultType
    >;
  };
  export type JSONSelectable = {
    [K in keyof Selectable]: Date extends Selectable[K]
      ? Exclude<Selectable[K], Date> | DateString
      : Date[] extends Selectable[K]
      ? Exclude<Selectable[K], Date[]> | DateString[]
      : Selectable[K];
  };
  export type UniqueIndex = 'faqs_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<
    Selectable,
    T[number]
  >;
  export type SQLExpression =
    | GenericSQLExpression
    | Table
    | Whereable
    | Column
    | ColumnNames<Updatable | (keyof Updatable)[]>
    | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

/* === cross-table types === */

export type Table = faqs.Table;
export type Selectable = faqs.Selectable;
export type Whereable = faqs.Whereable;
export type Insertable = faqs.Insertable;
export type Updatable = faqs.Updatable;
export type UniqueIndex = faqs.UniqueIndex;
export type Column = faqs.Column;
export type AllTables = [faqs.Table];

export type SelectableForTable<T extends Table> = {
  faqs: faqs.Selectable;
}[T];

export type WhereableForTable<T extends Table> = {
  faqs: faqs.Whereable;
}[T];

export type InsertableForTable<T extends Table> = {
  faqs: faqs.Insertable;
}[T];

export type UpdatableForTable<T extends Table> = {
  faqs: faqs.Updatable;
}[T];

export type UniqueIndexForTable<T extends Table> = {
  faqs: faqs.UniqueIndex;
}[T];

export type ColumnForTable<T extends Table> = {
  faqs: faqs.Column;
}[T];

export type SQLForTable<T extends Table> = {
  faqs: faqs.SQL;
}[T];
