const {
  REACT_APP_GOOGLE_ANALYTICS_ID,
  FOODFEED_EMAIL_ADDRESS,
  FOODFEED_SUPPORT_EMAIL,
  FOODFEED_CRASHES_EMAIL,
  REACT_APP_GAUTH_CLIENTID,
  GAUTH_CLIENT_SECRET,
  FOODFEED_GMAIL_REFRESH_TOKEN,
  NODE_ENV = 'dev',
  PORT = 8000,
  APN_KEY: APN_KEY_COMMA,
  APN_KEY_ID,
  APPLE_DEV_TEAM_ID,
  APPLE_BUNDLE_ID_STRING,
  FIREBASE_SERVER_KEY,
  JWT_SECRET,
  AWS_ACCESS_KEY_ID,
  AWS_ACCESS_KEY_SECRET,
  TRELLO_API_KEY,
  TRELLO_API_TOKEN,
  TRELLO_TECHNICAL_ISSUE_LIST_ID,
  TRELLO_SUPPORT_TICKET_LIST_ID,
  REDIS_URL,
  REDIS_PROD_CLUSTER_HOSTS,
  TURN_REST_API_SECRET,
  TURN_REST_API_URLS,
  AMPLITUDE_API_KEY,
  ETHAN_DB_USER_ID,
  ANI_DB_USER_ID,
  FOODFEED_DB_USER_ID,
  DATABASE_URL,
  FOODFEED_ADMIN_API_TOKEN
} = process.env;

const IS_PRODUCTION = NODE_ENV === 'production';

const APN_KEY = APN_KEY_COMMA?.replace(/,/gi, '\n');

const envs = [
  REACT_APP_GOOGLE_ANALYTICS_ID,
  FOODFEED_EMAIL_ADDRESS,
  FOODFEED_SUPPORT_EMAIL,
  FOODFEED_CRASHES_EMAIL,
  REACT_APP_GAUTH_CLIENTID,
  GAUTH_CLIENT_SECRET,
  FOODFEED_GMAIL_REFRESH_TOKEN,
  NODE_ENV,
  PORT,
  APPLE_BUNDLE_ID_STRING,
  APN_KEY,
  APN_KEY_ID,
  APPLE_DEV_TEAM_ID,
  FIREBASE_SERVER_KEY,
  JWT_SECRET,
  IS_PRODUCTION,
  AWS_ACCESS_KEY_ID,
  AWS_ACCESS_KEY_SECRET,
  TRELLO_API_KEY,
  TRELLO_API_TOKEN,
  TRELLO_TECHNICAL_ISSUE_LIST_ID,
  TRELLO_SUPPORT_TICKET_LIST_ID,
  REDIS_URL,
  TURN_REST_API_SECRET,
  TURN_REST_API_URLS,
  AMPLITUDE_API_KEY,
  ETHAN_DB_USER_ID,
  ANI_DB_USER_ID,
  FOODFEED_DB_USER_ID,
  DATABASE_URL,
  FOODFEED_ADMIN_API_TOKEN
];

if (!envs.every((env) => env !== undefined)) {
  throw new Error('Some environment variables are undefined');
}

const TURN_REST_API_URLS_ARRAY = TURN_REST_API_URLS!.split(',');
const REDIS_PROD_CLUSTER_HOSTS_ARRAY = REDIS_PROD_CLUSTER_HOSTS?.split(',').map(
  (host) => {
    return { host, port: 6379 };
  }
);

export {
  REACT_APP_GOOGLE_ANALYTICS_ID,
  FOODFEED_EMAIL_ADDRESS,
  FOODFEED_SUPPORT_EMAIL,
  FOODFEED_CRASHES_EMAIL,
  REACT_APP_GAUTH_CLIENTID,
  GAUTH_CLIENT_SECRET,
  FOODFEED_GMAIL_REFRESH_TOKEN,
  NODE_ENV,
  PORT,
  APPLE_BUNDLE_ID_STRING,
  APN_KEY,
  APN_KEY_ID,
  APPLE_DEV_TEAM_ID,
  AWS_ACCESS_KEY_ID,
  AWS_ACCESS_KEY_SECRET,
  FIREBASE_SERVER_KEY,
  JWT_SECRET,
  IS_PRODUCTION,
  TRELLO_API_KEY,
  TRELLO_API_TOKEN,
  TRELLO_TECHNICAL_ISSUE_LIST_ID,
  TRELLO_SUPPORT_TICKET_LIST_ID,
  REDIS_URL,
  REDIS_PROD_CLUSTER_HOSTS_ARRAY,
  TURN_REST_API_SECRET,
  TURN_REST_API_URLS_ARRAY,
  AMPLITUDE_API_KEY,
  ETHAN_DB_USER_ID,
  ANI_DB_USER_ID,
  FOODFEED_DB_USER_ID,
  DATABASE_URL,
  FOODFEED_ADMIN_API_TOKEN
};
